// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DesignData {

  /// <summary>Holder for reflection information generated from Enum.proto</summary>
  public static partial class EnumReflection {

    #region Descriptor
    /// <summary>File descriptor for Enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpFbnVtLnByb3RvEgpEZXNpZ25EYXRhKmcKClNhbXBsZVR5cGUSFAoQU0FN",
            "UExFX1RZUEVfTk9ORRAAEhUKEVNBTVBMRV9UWVBFX1RZUEUxEAESFQoRU0FN",
            "UExFX1RZUEVfVFlQRTIQAhIVChFTQU1QTEVfVFlQRV9UWVBFMxADQg1aCy9E",
            "ZXNpZ25EYXRhYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::DesignData.SampleType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum SampleType {
    /// <summary>
    /// 
    /// </summary>
    [pbr::OriginalName("SAMPLE_TYPE_NONE")] None = 0,
    /// <summary>
    ///Type1 
    /// </summary>
    [pbr::OriginalName("SAMPLE_TYPE_TYPE1")] Type1 = 1,
    /// <summary>
    ///Type2 
    /// </summary>
    [pbr::OriginalName("SAMPLE_TYPE_TYPE2")] Type2 = 2,
    /// <summary>
    ///Type3 
    /// </summary>
    [pbr::OriginalName("SAMPLE_TYPE_TYPE3")] Type3 = 3,
  }

  #endregion

}

#endregion Designer generated code
